version: '3.8'

services:
  user-service:
    build: ./services/user-service
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/user-service:/app
    depends_on:
      - postgres
      - redis

  course-service:
    build: ./services/course-service
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/course-service:/app
    depends_on:
      - postgres
      - mongodb

  notification-service:
    build: ./services/notification-service
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/notification-service:/app
    depends_on:
      - rabbitmq

  analytics-service:
    build: ./services/analytics-service
    ports:
      - '3004:3004'
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/analytics-service:/app
    depends_on:
      - elasticsearch

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app

  admin-dashboard:
    build: ./admin-dashboard
    ports:
      - '3005:3005'
    environment:
      - NODE_ENV=development
    volumes:
      - ./admin-dashboard:/app

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: forestryfive
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forestryfive
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:6
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  postgres-data:
  mongodb-data:
  redis-data:
  elasticsearch-data:
  rabbitmq-data: 